# Generated by Django 4.0.3 on 2023-10-24 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='automobile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='service_rest.automobilevo'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'scheduled'), ('arrived', 'arrived'), ('in progress', 'in progress'), ('finished', 'finished'), ('canceled', 'canceled')], default='scheduled', max_length=200),
        ),
        migrations.AlterField(
            model_name='technician',
            name='employee_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
